# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '30-SOPKATHON-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 30-SOPKATHON-iOS
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftLint'
  pod 'KakaoSDKLink' # 메시지(카카오링크)
  pod 'KakaoSDKTemplate' # 메시지 템플릿 
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'  # 사용자 관리
  pod 'lottie-ios'
  pod 'Kingfisher', '~> 5.0'
  pod 'Then'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'PanModal'
  pod 'Gedatsu', configuration: %w(Debug)
  pod 'SkeletonView'
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'RxGesture'
   pod 'RxRelay'
end


